---
- hosts: php
  sudo: yes

  tasks:

  - name: Install PHP with packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
      - php-xml
      - php-gd
    notify:
      - restart apache

  - name: Update Apache to process PHP files first
    lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      regexp: '^DirectoryIndex'
      line: 'DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
    notify:
      - restart apache

  handlers:
   - name: restart apache
     service: name=apache2 state=restarted