---
- hosts: php
  sudo: yes

  tasks:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
      - php-xml
      - php-gd
     notify:
      - restart apache

  handlers:
   - name: restart apache
     service: name=apache2 state=restarted