---
- hosts: php
  sudo: yes

  tasks:

  - name: Update Apache to process PHP files first
    lineinfile: dest=/etc/apache2/mods-enabled/dir.conf regexp="^DirectoryIndex" line="DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm" state=present
    notify:
      - restart apache

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted